# Generated by Django 2.1.7 on 2019-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Koleksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('gambar', models.CharField(max_length=200)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
