# Generated by Django 2.1.7 on 2019-02-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='koleksi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Signup.Signup'),
            preserve_default=False,
        ),
    ]
