# Generated by Django 2.1.7 on 2019-02-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_koleksi_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tipe', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tools', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='koleksi',
            name='tipe_koleksi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.Arttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='koleksi',
            name='tools',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.Tools'),
            preserve_default=False,
        ),
    ]
