# Generated by Django 2.1.7 on 2019-02-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190214_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koleksi',
            name='tools',
        ),
        migrations.AddField(
            model_name='arttype',
            name='tools',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.Tools'),
            preserve_default=False,
        ),
    ]
