# Generated by Django 2.1.7 on 2019-02-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20190214_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koleksi',
            name='harga',
        ),
    ]
