# Generated by Django 2.1.7 on 2019-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_koleksi_harga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arttype',
            name='icon',
        ),
        migrations.AddField(
            model_name='tools',
            name='icon',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
