# Generated by Django 2.1.7 on 2019-02-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20190214_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koleksi',
            name='gambar',
            field=models.ImageField(upload_to='Media_user'),
        ),
    ]
